apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      # requiredDuringSchedulingIgnoredDuringExecution:
      #   nodeSelectorTerms:
      #   - matchExpressions:
      #     - key: disktype
      #       operator: In
      #       values:
      #       # - ssd
      #       - ssssddd 

      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd           
  containers:
  - name: with-node-affinity
    image: nginx
    imagePullPolicy: IfNotPresent
